name: Image Air-Drop
on: [workflow_dispatch] # 手动触发
jobs:
  download-image:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |
          docker pull cnri/cordra:2.6.0
          docker save cnri/cordra:2.6.0 > cordra.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cordra-image-tar
          path: cordra.tar
